### PR TITLE
change all "衍合" to "变基"

### PR DESCRIPTION
**Pull request by networm**
I've used the command below

    find . -name "*.asc" -type f -exec sed -i "s/衍合/变基/g" {} \;

rebase 在许多书籍中都被翻译为“变基”，而不是“衍合”，包括不限于《Git 权威指南》、《Git版本控制管理（第2版）》；而且“衍合”这个词字面上看起来很晦涩难懂，读者第一次看见并不懂什么意思。

### CODE REVIEW

**Comment by YueLinHo** [comment]
Nice! But please re-send the PR to [progit2-zh](https://github.com/progit/progit2-zh) and close this PR.

**Comment by networm** [comment]
@YueLinHo I have already change rebase in [progit2-zh](https://github.com/progit/progit2-zh) by [change all "衍合" to "变基" by networm · Pull Request #85 · progit/progit2-zh](https://github.com/progit/progit2-zh/pull/85) and merged in.
My problem is to update the [ProGit v1](http://git-scm.com/book/zh/v1). I didn't want the wrong translation still exist in ProGit v1.

简单地说就是不能让第一版错误的“衍合”翻译误导其他人了；第二版翻译完成之前第一版都会存在，所以也需要修正这个问题。

**Comment by YueLinHo** [comment]
@networm 
了解! 感謝你的解釋! 原諒我的無知! :)

@jnavila 
For these reasons, I also hope this PR could be merged:

1. Can't bear that ```衍合``` still exists in ProGit v1.
The word ```衍合``` is really really difficult to understand for most Chinese people. (99.999%  I guess. :P )
And after knowing what rebase does, we still can't understand why ```衍合``` is used for rebase.
That's a problem. right?

2. ```变基``` is more popular.

3. ProGit V2 zh is not finished yet, v1 is still there, so we need to fix it in v1 ASAP.

Thanks. ^_^

**Comment by networm** [comment]
@YueLinHo 我觉得这可能是大家不同的语言习惯导致的，现在“变基”已经成为主流，所以想要把错误的消除掉，而且原文也说这是临时翻译的：

> （译注：rebase 的翻译暂定为“衍合”，大家知道就可以了。）

**Comment by YueLinHo** [comment]
@networm 

>（译注：rebase 的翻译暂定为“衍合”，大家知道就可以了。）

這個我很早以前就注意到了。 :smile: 
我只是不知道 v2 已經修正成「变基」了。

其實我考究過「衍合」，我個人覺得它太過文言文。
含意是相當不錯，但是就如你所說的「晦涩难懂」。

**Comment by networm** [comment]
@YueLinHo 简体中文的修正了，繁体中文的不太清楚。

**Comment by YueLinHo** [comment]
繁中的還在討論用哪一個
不過「衍合」基本上是被否決了

**Comment by networm** [comment]
@YueLinHo 建议用“变基”，这样你们再搜索到简体中文的资料时不会困惑。

**Comment by networm** [comment]
@ben We have discussed this question and have a final result. And the git official zh_CN translation  [git/zh_CN.po at master · git/git](https://github.com/git/git/blob/master/po/zh_CN.po) already use this. So I need to fix this problem in Pro Git v1.

**Pull request merged**
