### PR TITLE
Update 01-chapter2.markdown

### PR DESCRIPTION
**Pull request by 8loser**
"提供"->"提交"

### CODE REVIEW

**Comment by jnavila** [comment]
This version of the book is no longer updated. Please apply your changes to progit2

**Comment by YueLinHo** [comment]
Currently, there is no progit2-zh-tw repo yet, but there is a progit2-zh repo.
And I confirmed that part in progit2-zh reop, no typo there.
Please see [this article of last sentence](https://github.com/progit/progit2-zh/blob/master/book/02-git-basics/sections/recording-changes.asc#%E6%8F%90%E4%BA%A4%E6%9B%B4%E6%96%B0)

**Comment by jnavila** [comment]
OK, will merge, for this time...

**Comment by YueLinHo** [comment]
@jnavila Oh~  I am sorry. I did not want to push you to merge it. Just said what I did.

**Pull request merged**
