### PR TITLE
Added newline 

### PR DESCRIPTION
**Pull request by faxriddin**

### CODE REVIEW

**Comment by jnavila** [comment]
I have seen that you have switched to progit2. Can this pull request be closed?

**Comment by faxriddin** [comment]
Yes. But I can not to start progit2.  I do not see progit2-uz.  Can you help me on progit2?

**Comment by jnavila** [comment]
Just start to translate at least 3 to 4 sections of the book, then open an issue and ask for the creation of progit2-uz. Within a few days, an administrator of the project should reply.

**Comment by faxriddin** [comment]
I did not know about. Thank you!

**Pull request closed without merging**
