### PR TITLE
Update 08-git-and-other-scms

### PR DESCRIPTION
**Pull request by archermind**
Correct some typos in chapter 8 of zh version

### CODE REVIEW

**Comment by archermind** [comment]
@jnavila  I've fixed some typos in these two chapters, please consider to merge them.

**Comment by archermind** [comment]
if you don't merge anything, even correction of typos ?

**Comment by jnavila** [comment]
I will merge this PR, but I'd rather not work too much on the first edition of the book.

**Comment by hopbit** [comment]
@achermind Check this out:
* https://github.com/progit/progit2 
* https://github.com/progit/progit2-zh

**Comment by archermind** [comment]
@hopbit Thanks, I am planing to working on the 2nd Edition translation. But I think it's better to finish reading of the 1st Edition first then move on to the 2nd. I found some typos when I was reading the 1st so  I file this PR.

**Pull request merged**
