### PR TITLE
re-translate zh-tw

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Anybody here?

**Comment by jnavila** [comment]
we no longer merge heavy changes to this version of progit. Please push changes to the second edition of progit instead.

**Comment by PeterDaveHello** [comment]
@jnavila Sorry, but there is no Version 2 for Traditional Chinese now, and the current translation is not very okay, I'll respectfully suggest you to consider to merge this PR as an exception, would you please consider that? Thanks a lot.

**Comment by PeterDaveHello** [comment]
anybody here?

**Comment by PeterDaveHello** [comment]
thanks

**Comment by jnavila** [comment]
De nada. But I really insist on switching to the second edition :cop:

**Comment by PeterDaveHello** [comment]
Sure!

**Comment by YueLinHo** [comment]
@PeterDaveHello 
We are translating [the second edition zt-tw](https://github.com/progit/progit2-zh-tw), and discussing the consistency translated word [here](https://nchueecsec.hackpad.com/Git-Pro-2-hdsV2m1i7ab).
I have a quick review on this PR.
It would be good if these changes are in [the second edition zt-tw](https://github.com/progit/progit2-zh-tw).
Welcome to join us. ^_^

BTW, the word *repository* is translated to *版本控制倉庫*.
I know you make it consistency. That's good. :)
But, ATM, we'd like to translate it to *版本庫* more.

**Comment by PeterDaveHello** [comment]
Got it.

**Comment by PeterDaveHello** [comment]
@YueLinHo Do you have permission to add me in?

**Comment by YueLinHo** [comment]
@PeterDaveHello 
permission for what? hackpad for discussing consistency translated word?
IIRC, you just need to sign in, then you will see it.

**Comment by PeterDaveHello** [comment]
I meant the permission of the repo.

**Comment by YueLinHo** [comment]
The same way here.
fork, push your changes to your repo, pull request, play the review.

**Pull request merged**
